# -*- coding: utf-8 -*-
"""clientes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iAVeSlS6_UWwYTl9sEHtu9stV-YnTsO9

# Proyecto de Minería de Datos: Captación de Clientes Bancarios

El objetivo del presente trabajo es desarrollar un modelo predictivo que permita estimar si un cliente se convertirá o no en cliente del banco, a partir de variables sociodemográficas, financieras y datos de campañas de marketing.

Paso 2: Importar las librerías necesarias
"""

# Librerías para manejo de datos
import pandas as pd
import numpy as np

# Librerías para visualización
import matplotlib.pyplot as plt

# Librerías para machine learning
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.metrics import ConfusionMatrixDisplay

"""Paso 3: Subir los archivos CSV a Google Colab"""

#from google.colab import files

#uploaded = files.upload()

"""Paso 4: Leer los dataset"""

# Cargar datasets
train = pd.read_csv('banca_train.csv', sep=';')
test = pd.read_csv('banca_test.csv', sep=';')

"""Paso 5: Verificar que los datos se cargaron correctamente"""

# Mostrar primeras filas
train.head()

test.head()

"""Paso 6: Analizar la Estructura del Dataset"""

train.info()

train.describe()

"""Paso 7: Verificar valores nulos"""

train.isnull().sum()

test.isnull().sum()

"""Paso 8: Analizar la variable objetivo"""

train['y'].value_counts()

train['y'].value_counts(normalize=True) * 100

"""Paso 9: Visualizar la variable objetivo"""

train.columns

train['y'].value_counts().plot(kind='bar')

plt.title('Distribución de clientes convertidos')
plt.xlabel('Conversión')
plt.ylabel('Cantidad')
plt.show()

"""Paso 10: Separar variables predictoras y variable objetivo"""

X_train = train.drop('y', axis=1)
y_train = train['y']

X_test = test.drop('y', axis=1)
y_test = test['y']

"""Paso 11: Transformar variables categóricas"""

## Crear encoder
le = LabelEncoder()

# Transformar columnas categóricas
for col in X_train.columns:
    if X_train[col].dtype == 'object':

        # Ajustar encoder en train
        X_train[col] = le.fit_transform(X_train[col])

        # Aplicar transformación en test
        X_test[col] = le.transform(X_test[col])

# Transformar variable objetivo
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

X_train.head()##

# Transformar variables categóricas con One Hot Encoding
X_total = pd.concat([X_train, X_test], axis=0)

X_total = pd.get_dummies(X_total, drop_first=True)

X_train = X_total.iloc[:len(X_train), :]
X_test = X_total.iloc[len(X_train):, :]

# Transformar variable objetivo
y_train = pd.Series(y_train).replace({'no': 0, 'yes': 1})
y_test = pd.Series(y_test).replace({'no': 0, 'yes': 1})

"""Paso 12: Entrenar el modelo de Machine Learning.
🌳 Árbol de Decisión (Decision Tree)
"""

# Crear modelo
modelo = DecisionTreeClassifier(random_state=42)

# Entrenar modelo
modelo.fit(X_train, y_train)

"""Paso 13: Realizar predicciones"""

# Generar predicciones
y_pred = modelo.predict(X_test)

"""Paso 14: Crear la matriz de confusión"""

# Matriz de confusión
cm = confusion_matrix(y_test, y_pred)

cm

"""Paso 15: Visualizar la matriz de confusión"""

# Mostrar matriz de confusión
disp = ConfusionMatrixDisplay(confusion_matrix=cm)

disp.plot()

plt.title('Matriz de Confusión')
plt.show()

"""Paso 16: Calcular el Accuracy del modelo"""

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy del modelo:", accuracy)

"""Paso 17: Obtener métricas completas"""

# Reporte de clasificación
print(classification_report(y_test, y_pred))

"""Paso 18: Eliminar la variable duration"""

# Eliminar variable duration
X_train2 = X_train.drop('duration', axis=1)
X_test2 = X_test.drop('duration', axis=1)

"""Paso 19: Entrenar nuevamente el modelo SIN duration"""

# Crear nuevo modelo
modelo2 = DecisionTreeClassifier(random_state=42)

# Entrenar modelo sin duration
modelo2.fit(X_train2, y_train)

"""Paso 20: Generar nuevas predicciones"""

# Predicciones del nuevo modelo
y_pred2 = modelo2.predict(X_test2)

"""Paso 21: Calcular nueva matriz de confusión y accuracy"""

# Nueva matriz de confusión
cm2 = confusion_matrix(y_test, y_pred2)

# Accuracy nuevo
accuracy2 = accuracy_score(y_test, y_pred2)

print("Nuevo Accuracy:", accuracy2)
print(cm2)

"""Paso 22: Ver nueva matriz gráficamente"""

disp = ConfusionMatrixDisplay(confusion_matrix=cm2)

disp.plot()

plt.title('Matriz de Confusión SIN duration')
plt.show()

"""Paso 23: Obtener nuevas métricas"""

print(classification_report(y_test, y_pred2))

"""Paso 24: Importar métricas ROC"""

# Probabilidades de pertenecer a la clase positiva
y_prob = modelo2.predict_proba(X_test2)[:,1]

"""Paso 26: Calcular curva ROC y AUC"""

from sklearn.metrics import roc_curve, roc_auc_score

# Calcular curva ROC
fpr, tpr, thresholds = roc_curve(y_test, y_prob)

# Calcular AUC
auc = roc_auc_score(y_test, y_prob)

print("AUC:", auc)

"""Paso 27: Graficar la Curva ROC"""

plt.figure(figsize=(8,6))

plt.plot(fpr, tpr, label='ROC Curve (AUC = %0.2f)' % auc)

plt.plot([0,1], [0,1], linestyle='--')

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')

plt.title('Curva ROC')

plt.legend()

plt.show()